modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="apotheosis"

version="8.0.0-alpha0"

displayName="Apotheosis"

authors="Shadows_of_Fire"

description='''All things that should have been'''

[[mixins]]
config="apotheosis.mixins.json"

[[dependencies.apotheosis]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.61,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="placebo"
    type="required"
    versionRange="[9.5.5-beta14,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="apothic_attributes"
    type="required"
    versionRange="[2.4.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="apothic_spawners"
    type="required"
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.apotheosis]]
    modId="apothic_enchanting"
    type="required"
    versionRange="[1.2.4-beta0,)"
    ordering="AFTER"
    side="BOTH"
